spring:
  application:
    name: menu-service

server:
  port: 9003
  servlet:
    session:
      timeout: 60m
      persistent: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka